### PR TITLE
check markdown in travis build

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@FooDeas the default base branch is master when you open a pull request, I think that should change to `devel` because I now have to change it manually.

**Comment by FooDeas** [comment]
Default branch is changed to devel.

**Comment by thijstriemstra** [comment]
> Do we really need the exclusions of shellcheck and markdown rules?

Think so @FooDeas, try running them without (line-length then has to be < 80 triggering many errors for example and I found other errors not useful). The `~` means they're excluded for mdl.

**Comment by FooDeas** [comment]
I see! Then I suggest the following` .travis.yml` config:
```
language: bash
install: gem install mdl
script:
 - bash -c 'shopt -s globstar; shellcheck **/*.sh'
 - mdl -r '~MD013, ~MD036' .
```
I'd like to fix the docs for MD013 and MD036 piece by piece.

**Comment by thijstriemstra** [comment]
@FooDeas changed it but expecting the build to fail now. Feel free to fix these in this branch or elsewhere.

**Pull request merged**
