### PR TITLE
Hide passwords in the log output

### PR DESCRIPTION
**Pull request by ghost**
This pull request proposes to hide the root and user passwords in the log output.
People unfortunately often do not realize that they may leak sensitive security information when posting their logfiles on the world wide web.

I have replaced the password output with a * but if you want to have another text or if you prefer to simply remove the lines with the password output, just let me know and I will update it.

### CODE REVIEW

**Comment by FooDeas** [comment]
Hmm... Permission is 600 with root owner. I thought it useful to have a printout while installing.

We could also cut it after x chars!?

**Comment by ghost** [comment]
In general I am not very happy when passwords are stored on the filesystem as clear-text (unencrypted).
Three locations are affected from this issue:

1.) The passwords are stored in the 'installer-config.txt'-file on the boot-partition (if manually entered by the user).
However there is also a cleanup-option in this file that can be used to remove the whole configuration directory after installation, so this is OK from my point of view.

2.) The passwords are stored in the '/var/log/raspberrypi-ua-netinst.txt'-file if the installation was successful.
There is also a cleanup-option for this file, however with this option a lot of useful log-information will be lost.

3.) The passwords are stored in the error-log on the boot-partition if the installation fails and I am not sure if all users of this installer are aware about that fact when they are sharing this file on the world wide web in the hope to get support for their problem.

I am not very happy with the "cut it after x chars" approach because this still leaks part of the password (or maybe even the whole password if it is very short).

Another idea is to keep the password-printouts as it is in the display output during installation but before the output is written to the logfile on the filesystem we delete the lines that contain the passwords (with the sed command).
Would that be acceptable from your side?

**Comment by Mausy5043** [comment]
You could use the `output_filter()` in `install.sh` to filter the passwd out?

**Comment by FooDeas** [comment]
👍

**Pull request merged**
