### PR TITLE
add travis build

### PR DESCRIPTION
**Pull request by thijstriemstra**
this adds a travis build that uses shellcheck to verify the scripts.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@FooDeas can you enable travis for the repository so this pull request can be tested?

**Comment by thijstriemstra** [comment]
@FooDeas can you enable travis for this repository on https://travis-ci.org/?, e.g. https://travis-ci.org/FooDeas/raspberrypi-ua-netinst

**Comment by FooDeas** [comment]
done

**Comment by thijstriemstra** [comment]
@FooDeas it's failing because the update script uses an unrecognized option '--show-progress'  (only available in [wget 1.16](https://savannah.gnu.org/forum/forum.php?forum_id=8133) and travis uses 1.15). Because travis is headless I also expect this to screw up when running in headless mode. Because [travis sets](https://travis-ci.org/FooDeas/raspberrypi-ua-netinst/builds/331965350#L441) the `export DEBIAN_FRONTEND=noninteractive` env var I thought we could check for this and remove the --show-progress if it's noninteractive. I also look into getting a newer wget version on travis but this isn't as easy it seems. Or it should be removed if wget < 1.16.. Thoughts?

See https://travis-ci.org/FooDeas/raspberrypi-ua-netinst/builds/331965350#L597

**Comment by thijstriemstra** [comment]
Fixed it by installing a newer wget (1.18) on travis. Will now setup some sane caching.

**Comment by FooDeas** [comment]
Nice work! Tell me when it's finished.

**Comment by thijstriemstra** [comment]
I'm not sure if this pull request makes sense in hindsight, because it basically downloads a lot of packages (that can fail quite often) and runs a build.. thoughts?

**Comment by thijstriemstra** [comment]
@FooDeas should be ready. It basically checks the .sh scripts using shellcheck.

**Comment by FooDeas** [comment]
That was a really great idea!!

**Pull request merged**
