### PR TITLE
Upgrade to Bullseye and support for arm64 architecture

### PR DESCRIPTION
**Pull request by ondrej-zary**

### CODE REVIEW

**Comment by FooDeas** [comment]
Looks good! I have to try it out!

**Comment by ondrej-zary** [comment]
Tested only on Raspberry 4. I also have Raspberry 1 but haven't tested it due to lack of time.

**Comment by ondrej-zary** [comment]
I've tested a 32-bit model and it was broken because the firmware fails to boot when arm_64bit=1 is set (instead of just ignoring it as the CPU is 32-bit only). Fixed now and tested on original Model B.

**Comment by FooDeas** [comment]
WiFi installation with model 3B fails because the interface is not present. Can you have a look?
I think, the firmware files are missing...

**Comment by ondrej-zary** [comment]
Fixed in 7029fcb50fcf4de9c12356c028109db0e87f6d3c. There are two other commits before: 0edaaaf8fe5cb07bd62607dc9589d3ed9412925a and 9a15a1c757bcc08f8a42bf3f612b9d425d7ca1e4.

**Comment by FooDeas** [comment]
@ondrej-zary I have to thank you again for your work and contribution!
I made some changes and improvements and was able to do a new release based on this. Some of your code was the solution of "issues" that always annoyed me. Again: Thank you very much!

**Comment by ondrej-zary** [comment]
Thank you for keeping this tool alive.
Very useful for embedded use, much better than bloated official images.

**Comment by mike632t** [comment]
> Thank you for keeping this tool alive. Very useful for embedded use, much better than bloated official images.

I'll second that !

**Pull request merged**
