### PR TITLE
create netdev group

### LINKED ISSUE #198: Installer doesn't like `DIR=/var/run/wpa_supplicant GROUP=netdev` in wpa_supplicant.conf
Here is the log while trying to build on a RPi 3B+ via WiFi:

```
==================================================
raspberrypi-ua-netinst
==================================================
Revision 685148f
Built on Sat 11 Jul 2020 09:55:22 AM CEST
Running on Raspberry Pi version 3 Model B+
==================================================
https://github.com/FooDeas/raspberrypi-ua-netinst/
==================================================
Remounting TempFS... OK
Mounting boot partition... OK
Copying boot files... OK
Executing installer-config.txt...
OK

Searching for deprecated variables...

Checking if config.txt needs to be modified before starting installation...
  Setting HDMI options... OK
OK

Unmounting boot partition... OK

Network configuration:
  ifname = wlan0
  ip_addr = dhcp
  online_config = 

Waiting for wlan0... 1.. OK
Starting wpa_supplicant...
  Successfully initialized wpa_supplicant
  CTRL: Invalid group 'netdev'
  Failed to initialize control interface 'DIR=/var/run/wpa_supplicant GROUP=netdev'.
  You may have another wpa_supplicant process already running or the file was
  left by an unclean termination of wpa_supplicant in which case you will need
  to manually remove this file before starting wpa_supplicant again.
  
  nl80211: Failed to open /proc/sys/net/ipv6/conf/wlan0/drop_unicast_in_l2_multicast: No such file or directory
  nl80211: Failed to set IPv6 unicast in multicast filter
  nl80211: Failed to open /proc/sys/net/ipv6/conf/wlan0/drop_unicast_in_l2_multicast: No such file or directory
  nl80211: Failed to set IPv6 unicast in multicast filter
  nl80211: deinit ifname=wlan0 disabled_11b_rates=0
  nl80211 driver didn't work. Trying generic driver (wext)...
  Successfully initialized wpa_supplicant
  ioctl[SIOCSIWENCODEEXT]: Invalid argument
  ioctl[SIOCSIWENCODEEXT]: Invalid argument
  CTRL: Invalid group 'netdev'
  Failed to initialize control interface 'DIR=/var/run/wpa_supplicant GROUP=netdev'.
  You may have another wpa_supplicant process already running or the file was
  left by an unclean termination of wpa_supplicant in which case you will need
  to manually remove this file before starting wpa_supplicant again.
  

Error: The installation could not be completed!
```

 * Removing the line `DIR=/var/run/wpa_supplicant GROUP=netdev` from the `wpa_supplicant.conf` results in a successful build.
 * Interestingly, re-adding the line on the installed system works perfectly.

### PR DESCRIPTION
**Pull request by Mausy5043**
This should fix #198.

### CODE REVIEW

**Comment by Mausy5043** [comment]
Please stand by while testing this fix.

**Comment by Mausy5043** [comment]
Build was succesfull.   
Installer does not want to cooperate.

[BusyBox](https://busybox.net/downloads/BusyBox.html) manual says there is an `addgroup` command but trying to use it during the install yields `addgroup: command not found`

**Comment by Mausy5043** [comment]
These directives were supplied to the installer (apart from `network=`):
```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=NL
```

The first line was previously cause for aborting the installer (#198).

- [x] Build was succesfull (modification inserted correctly)
- [x] Install succesfull (WIFI connection acquired using the extended `wpa_supplicant.conf` file)
- [x] Installed system working as expected.

**Comment by FooDeas** [comment]
Thank you very much!

**Pull request merged**
