### PR TITLE
Support for Stretch

### PR DESCRIPTION
**Pull request by malignus**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@malignus thanks for the pull request. Unfortunately you made it against the `master` branch and we use a `dev` branch for development that later gets merged to master. Could you make the PR against the `dev` branch instead? We should document this..

**Comment by FooDeas** [comment]
I'll handle the target branch, review and merge this hopefully tomorrow.

Many thanks @malignus!! I canceled searching for dependencies after 2/3...

**Comment by FooDeas** [comment]
In some cases, WiFi is broken during installation and I have to clean this up a bit. I merge it in devel_stretch branch and work on it.

**Comment by malignus** [comment]
@FooDeas,
I found out that two firmware files are missing go get WiFi working.

`brcmfmac43430-sdio.bin
brcmfmac43430-sdio.txt`

After placing the files into `/lib/firmware/brcm` WiFi will work.

**Comment by FooDeas** [comment]
It was only a problem with an libssl v1.1 is needed as well.

**Pull request merged**
